### PR TITLE
74 fix timezone bug

### LINKED ISSUE #74: Update POST that take "time" to convert based on time zone

### PR DESCRIPTION
**Pull request by Q-Win**
- [x] Wrote Tests
- [x] Implemented
- [x] Reviewed

# Necessary checkmarks:
- [x] All Tests are Passing
- [x] The code will run locally

## Type of change
- [ ] New feature
- [x] Bug Fix

# Implements/Fixes:
## Description of Changes

closes #74 

# Check the correct boxes
- [x] This broke nothing
- [ ] This broke some stuff
- [ ] This broke everything

# Testing Changes
- [ ] No Tests have been changed
- [x] Some Tests have been changed
- [ ] All of the Tests have been changed(Please describe what in the world happened)

# Checklist:

- [ ] My code has no unused/commented out code
- [ ] I have reviewed my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have fully tested my code

### CODE REVIEW

File: app/controllers/api/v1/day_summary_controller.rb [hunk 1]
```diff
@@ -1,8 +1,8 @@
 class Api::V1::DaySummaryController < ApplicationController
 
   def show
-
-    begin_time_range = params[:date].to_i - (params[:date].to_i % 86400)
+    #7*3600 is 7 hours worth of seconds. 7 a.m. in England and 12 a.m. in Denver
+    begin_time_range = params[:date].to_i - (params[:date].to_i % 86400) +(7*3600)
```
Comment (prestonjarnagin) [inline app/controllers/api/v1/day_summary_controller.rb:5]: 😱😢

**Review by prestonjarnagin — APPROVED** [review]
This works for now, but we'll probably need to find a more sustainable solution in the long-term
